lsst-sqre/documenteer

documenteer/designdocs/ddconfig.py
setup.py

This lets technotes use Sphinx extensions from documenteer itself.

Add documenteer.sphinext to technote sphinx extension list

---

.travis.yml
CHANGELOG.rst
README.rst
documenteer/sphinxconfig/utils.py
setup.py
tests/test_sphinxconfig_utils.py

- Add auto deployment to PyPI via Travis
- Add `form_ltd_edition_name()` function to make friendly version strings.

DM-6120: v0.1.11

---

CHANGELOG.rst
documenteer/sphinxconfig/technoteconf.py
documenteer/sphinxconfig/utils.py
tests/test_sphinxconfig_utils.py
tests/test_technoteconf.py

- Rename the configuration function for technotes: `documenteer.sphinxconfig.technoteconfig.configure_sphinx_design_doc` is now `documenteer.sphinxconfig.technoteconfig.configure_technote`.
- Sphinx is no longer in the default intersphinx object list for technotes.
This will speed up builds for documents that don't refer to Python APIs, and is still straightforward to configure on a per-project basis.
- The default revision timestamp for technotes is now derived from the most recent Git commit that modified a technote's content ('rst', and common image file formats).
This is implemented with the new `documenteer.sphinxconfig.utils.get_project_content_commit_date` function.
This feature allows us to change technote infrastructure without automatically bumping the default revision date of …

DM-11334: Technote configuration improvements

---

CHANGELOG.rst
documenteer/bin/refreshlsstbib.py
documenteer/sphinxconfig/technoteconf.py
documenteer/sphinxext/__init__.py
documenteer/sphinxext/bibtex.py
setup.py
tests/test_refreshlsstbib.py

- Add `LsstBibtexStyle` pybtex style to support DocuShare fields (from lsst-texmf originally).
- Add `refresh-lsst-bib` program to download lsst-bibtex files from GitHub (master branch). This is a lightweight way of helping people automatically update their lsst-bibtex files without the usability issues of submodules.

DM-6033: Support for lsst-texmf bibliographies

---

CHANGELOG.rst
documenteer/sphinxext/lsstdocushare.py
setup.py
tests/test_sphinxext_lsstdocushare.py

Support for
- LTS
- LEP
- LCA
- LSSTC
- LCR
- LCN
- DMTR
- SPT
- Document (displays in title case, Document-1)
- Report (displays in title case)
- Minutes (displays in title case)
- Collection (displays in title case)
- SQR
- DMTN
- SMTN

DM-11415: Additional roles for creating ls.st links to DocuShare handles

---

.travis.yml
setup.cfg
setup.py

This avoids unnecessarily polluting a development environment.
Eg., `python setup.py test`

add ability to run tests without installing

---

CHANGELOG.rst
LICENSE
documenteer/sphinxext/__init__.py
documenteer/sphinxext/packagetoctree.py
setup.py
tests/test_sphinxext_packagetoctree.py

These new directives are primarily for https://github.com/lsst/pipelines_lsst_io to create dynamic tables of contents for packages.
Create a toctree of `modules` with
```rst
.. module-toctree::
```
Create a toctree of `packages` with
```rst
.. package-toctree::
```

DM-14053: Add package-toctree and module-toctree

---

CHANGELOG.rst
documenteer/sphinxrunner.py
documenteer/stackdocs/build.py
documenteer/stackdocs/packagecli.py
documenteer/stackdocs/stackcli.py
setup.py

- New `stack-docs` command-line app. This replaces `build-stack-docs`, and now provides a subcommand interface: `stack-docs build` and `stack-docs clean`.
- New `package-docs` command-line app. This CLI complements `stack-docs`, but is intended for single-package documentation. This effectively lets us replace the Sphinx Makefile (including the `clean` command). Using a packaged app lets us avoid SIP issues, as well as Makefile drift in individual packages.
- Refactored the Sphinx interface into `documenteer.sphinxrunner.run_sphinx`. This change lets multiple command-line front-ends to drive Sphinx.
Fixes #18

DM-14095: Add stack-docs and package-docs command line apps

---

documenteer/sphinxconfig/technoteconf.py
documenteer/sphinxconfig/utils.py

I had a bunch of other files lying around in my repository, and every time I typed `make` I got a screenfull of warnings about files for which we couldn't get a commit, which was annoying.
This is a quick & dirty attempt to fix the issue. I am not deeply enough immersed in Documenteer culture to know whether this is appropriate, but it seems to work for me...

Include exclude_patterns in VCS version check

---

documenteer/sphinxext/packagetoctree.py

`module-toctree` and `package-toctree` are now sorted.

DM-14773: Sort package and module toctree listings

---

CHANGELOG.rst
documenteer/requestsutils.py
documenteer/sphinxext/__init__.py
documenteer/sphinxext/remotecodeblock.py
setup.py

The `remote-code-block` directive is implemented as a subclass of `literalinclude`. The only difference is that the file reader code is swapped for requests.get so that it fetches code files over the web.
This code uses the requests_retry_session session builder to ensure that GETs are retried.
Also includes `requests_retry_session` from https://www.peterbe.com/plog/best-practice-with-retries-with-requests to robustly retry GETs that fail due to network errors.

DM-14777: Add remote-code-block directive

---

CHANGELOG.rst
documenteer/stackdocs/packagecli.py
documenteer/stackdocs/rootdiscovery.py
documenteer/stackdocs/stackcli.py
tests/test_stackdocs_rootdiscovery.py

Users will need to set the --dir option of stack-docs and package-docs CLIs less often with this PR.
For stack-docs, as long as the CWD is `pipelines_lsst_io`, or a subdirectory of it, the CLI should find the conf.py file.
For package-docs the doc/conf.py file is discovered as long as:
- the package's root directory
- the doc/ directory
- a subdirectory of doc/
Fixes #28

DM-14805: allow stack-docs and package-docs CLI to discover conf.py

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py
documenteer/sphinxconfig/technoteconf.py
documenteer/stackdocs/build.py

If a stack package or technote doesn't have a `_static` directory, it won't be added to the `html_static_path` Sphinx configuration (via `documenteer.sphinxconf`) and thus won't generate a warning at build time.

DM-15006: Make _static optional

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py

These are python dependencies for the LSST Science PIpelines.

DM-15013: Add scikit-learn and pandas to stack intersphinx

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py
setup.py

- Version 0.3.0 release
- Includes a re-pinning of Sphinx to <1.8.0 to avoid an incompatibility with `documenteer.sphinxrunner`.

DM-15802: Release 0.3.0

---

CHANGELOG.rst
docs/sphinxext/lssttasks.rst
documenteer/sphinxext/lssttasks/__init__.py
documenteer/sphinxext/lssttasks/pyapisummary.py

This PR adds a directive that generates a summary of the Python API for a task class. This is meant to be used in task topic pages to bridge task documentation to the autodoc-generated API reference documentation for the task class.
Usage:
```rst
Python API summary
==================
.. lsst-task-api-summary:: lsst.pipe.tasks.assembleCoadd.AssembleCoaddTask
```

DM-15777: Directive that summarizes a Task's Python API

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py

- Added Astropy to the intersphinx configuration.
- Enabled `automodsumm_inherited_members` in the stackconf for stack documentation. This configuration is critical:
1. It is actually responsible for ensuring that inherited members of classes appear in our docs.
2. Without this, classes that have a `__slots__` attribute (typically through inheritance of a `collections.abc` class) won't have *any* of their members documented. See https://jira.lsstcorp.org/browse/DM-16102 for discussion.
This is a back port intended for a 0.3.x release.

DM-16102: Enable automodsumm_inherited_members (0.3 backport)

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py

- Added Astropy to the intersphinx configuration.
- Enabled `automodsumm_inherited_members` in the stackconf for stack documentation. This configuration is critical:
1. It is actually responsible for ensuring that inherited members of classes appear in our docs.
2. Without this, classes that have a `__slots__` attribute (typically through inheritance of a `collections.abc` class) won't have *any* of their members documented. See https://jira.lsstcorp.org/browse/DM-16102 for discussion.

DM-16102: Enable automodsumm_inherited_members

---

CHANGELOG.rst
docs/conf.py
documenteer/sphinxconfig/stackconf.py

Release for 0.4.0, which includes the new task documentation extensions, and also hides todo entries from the pipelines.lsst.io build.

Release 0.4.0

---

CHANGELOG.rst
documenteer/sphinxext/lssttasks/taskutils.py

- Substitute in "Undocumented." as the docstring.
- Generate a warning message.
This can be released as documenteer 0.4.2.

DM-16398: Handle missing docstrings in get_docstring

---

CHANGELOG.rst
documenteer/sphinxext/lssttasks/configfieldlists.py

If an item in an `lsst.pex.config.Registry` is wrapped in a `ConfigurableWrapper` than it does not have `__module__` and `__name__` attributes like most tasks seem to. Instead, the task itself is accessible from a `_target` attribute on the `ConfigurableWrapper`.
To handle the most generic case, the introduction can also fall back to accessing the `__class__` attribute and getting the `__module__` and `__name__` attributes from that.

DM-17661: Support ConfigurableWrapper-type items in lsst-task-config-subtasks

---

CHANGELOG.rst
documenteer/stackdocs/build.py
tests/test_stackdocs_build.py

Before, EUPS packages would be incorporated into the stack documentation build if they were set up by EUPS _and_ had a `doc/manifest.yaml` file. Now packages must all be explicitly required (`setupRequired`) by the EUPS table file of the main documentation repository.
This change prevents dependencies of the stack project, which are not actually released with that project, from being automatically incorporated into documentation.

DM-17765: Filter packages by the EUPS table file

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py
documenteer/sphinxconfig/utils.py
documenteer/sphinxext/lssttasks/configfieldlists.py
documenteer/sphinxext/lssttasks/taskutils.py
setup.py
tests/test_sphinxconfig_stackconf.py

From the change log:
- This release adds the `sphinx-jinja`_ extension for ``documenteer[pipelines]`` installations.
This extension makes it possible to dynamically create content with Jinja templating.
- The ``documenteer.sphinxconfig.stackconf`` module sets up a ``default`` context for the ``jinja`` directive that includes all module attributes in the Sphinx config module.
- The ``documenteer.sphinxconfig.stackconf`` module includes several new configuration attributes that are driven by the presence of an ``EUPS_TAG`` environment variable.
The overall intent of these variables is to make it possible to render installation documentation for the https://pipelines.lsst.io documentation project from the ``EUPS_TAG`` environment variable.
The variables are:
- ``release_eups_tag``
- …

DM-17065: Add sphinx-jinja extension and EUPS_TAG-driven variables for pipelines.lsst.io installation

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py

- The logotext for single package builds is now the name of the project configured through the `doc/conf.py` file
- Fix the double full-stop issue on copyrights
- Add `astro_metadata_translator` and `firefly_client` to the intersphinx inventory of pipelines documentation projects.

DM-17263: Improve single package builds and version 0.5.0 release

---

CHANGELOG.rst
LICENSE
docs/conf.py
setup.py

docutils 0.15 came out and it breaks the `jira*` roles. Sphinx doesn't strongly pin docutils, so let's pin it through documenteer until the role can be fixed.

Pin docutils to 0.14

---

.travis.yml
CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py
setup.py

This lets us use the `argparse` directive from [sphinx-argparse](https://github.com/ribozz/sphinx-argparse) in pipelines documentation to autodocument ad hoc scripts.

DM-20767: Add sphinx-argparse 0.2.x for pipelines

---

CHANGELOG.rst
documenteer/sphinxext/jira.py
setup.py

Understanding that docutils 0.15 [isn't supported](https://github.com/lsst-sqre/documenteer/blob/03f21ce02a1fb2e15b8a186ce299380c345b36eb/setup.py#L34)... I found I had to make this change to make it work. I hope it's useful.

Fix to run with docutils 0.15.

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py

- Enabled the `html_use_index` and `html_domain_indices` configurations for Stack documentation projects to enable automatic index generation. The `genindex` contains links to all command-line options and Python objects (Sphinx's domains). This also opens us up to a more general content index by way of the [index directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=index#index-generating-markup).
- Also updated the intersphinx URL for Pandas to use https.

DM-20850: Enable index generation for Pipelines documentation

---

CHANGELOG.rst
setup.py

This new version of the technote sphinx theme should fix the edition link in the sidebar for non-main editions.

DM-20839: Update lsst-dd-rtd-theme to 0.2.2 (0.5.4 release)

---

CHANGELOG.rst
docs/conf.py
documenteer/sphinxext/jira.py
setup.py

This new version of the technote sphinx theme should fix the edition link in the sidebar for non-main editions.

DM-20839: Update lsst-dd-rtd-theme for 0.2.2 (0.4.6 release)

---

CHANGELOG.rst
documenteer/sphinxconfig/technoteconf.py

Technote configuration now uses ``yaml.safe_load`` instead of ``yaml.load``. See the [pyyaml docs for details](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).
Closes #63

DM-22537: Use yaml.safe_load (0.5.5 release)

---

CHANGELOG.rst
documenteer/sphinxconfig/technoteconf.py

Technote configuration now uses ``yaml.safe_load`` instead of ``yaml.load``. See the [pyyaml docs for details](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).
See #73 for the mainline PR.
Closes #63

DM-22537: Use yaml.safe_load (0.4.7 release)

---

.travis.yml
CHANGELOG.rst
setup.py

The goal of this work is to bring documenteer and LSST's Sphinx documentation stack up to date with Sphinx 2.x.
Fixes #47 
- Documenteer now works with Sphinx 2.0+.
By default, Documenteer will install the latest version of Sphinx for you.
Other dependency upgrades:
- The ``click`` version now floats.
- ``numpydoc`` is pinned at 0.8.0.
- ``sphinx-automodapi`` is pinned at 0.12.
- ``breathe`` is pinned at 4.14.0.
Updates to development or test dependencies:
- pytest is pinned to 4.5.0.
- sphinx-click is pinned to 2.3.1.
- Python 3.6 is no longer officially supported.
Documenteer is tested with Python 3.7.

DM-22533: Compatibility with Sphinx 2

---

.gitignore
.travis.yml
CHANGELOG.rst
docs/conf.py
documenteer/conf/technote.py
documenteer/sphinxext/lssttasks/configfieldlists.py
documenteer/sphinxext/packagetoctree.py
documenteer/sphinxrunner.py
setup.cfg
setup.py

Added static type checking using [pytest-mypy](https://github.com/dbader/pytest-mypy). The goal in this PR is to add type checking to the CI tests and to modify the code as lightly as possible to make this happen.
I'm using the `ignore_missing_imports = True` flag to avoid adding stubs for third-party packages at this point.

DM-22717: Add mypy type checking

---

.travis.yml
CHANGELOG.rst
setup.py

This PR drops the use of pytest-runner from the Documenteer 0.5 release line. pytest-runner as a whole is deprecated, and it's also interfering with the Conda build of Documenteer.

DM-23095: Drop the use of pytest-runner (0.5.6 release)

---

CHANGELOG.rst
setup.py

The [Click](https://click.palletsprojects.com/en/7.x/) dependency is no longer pinned (previously it was pinned `<=7`).
This improves compatibility with installations that also include cookiecutter, which requires click 7+.
For release as 0.5.7.

DM-23661: Unpin click dependency in 0.5 series

---

.gitignore
CHANGELOG.rst
docs/install.rst
docs/sphinx-extensions/autocppapi.rst
docs/sphinx-extensions/index.rst
documenteer/conf/pipelines.py
documenteer/ext/autocppapi.py
setup.cfg
tests/conftest.py
tests/roots/test-autocppapi/conf.py
tests/roots/test-autocppapi/doxygen.tag.zip
tests/roots/test-autocppapi/index.rst
tests/test_ext_autocppapi.py

The `autocppapi` directive is the C++ equivalent of the `automodapi` we use for listing Python APIs. It's made to integrate with the doxylink extension. Example:
```rst
.. autocppapi:: lsst::afw::table
```
This lists classes, structs, etc. that include `lsst::afw::table`` in their signature.

DM-22461: Add an autocppapi directive that lists contents in a C++ namespace

---

.github/workflows/ci.yaml
CHANGELOG.rst
documenteer/conf/pipelines.py
documenteer/sphinxrunner.py
setup.cfg

- Remove pins on `[pipelines]` extra to better keep up with third-party improvements.
- For `[pipelines]`, pin the Sphinx version as <3, >2 because of an automodapi incompatibility with Sphinx 3. This is already resolved on their master branch, and thus we're awaiting a 0.13 release of automodapi.
- Add the sphinx_click extension to the `[pipelines]` extra.

DM-26768: Remove pins on [pipelines] extra dependencies 

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
CHANGELOG.rst
docs/pipelines/cpp-api-linking.rst
docs/sphinx-extensions/autocppapi.rst
documenteer/conf/technote.py
documenteer/sphinxconfig/technoteconf.py
setup.cfg

- Documenteer works with the latest version of `sphinxcontrib-bibtex`_. Both the new (``documenteer.conf.technote``) and old (``documenteer.sphinxconfig.technoteconf``) versions of the technote configuration use the new ``bibtex_bibfiles`` configuration variable. Version 2.0.0 or later of `sphinxcontrib-bibtex`_ is now required because of that package's API.

DM-28543: Compatibility with sphinxcontrib-bibtex 2.0+

---

.github/workflows/ci.yaml
CHANGELOG.rst
README.rst
setup.cfg
tox.ini

- Fix a reStructuredText error in the long description
- Add a "packaging" environment to tox to explicitly build the package and run `twine check`. This is a more robust pre-flight of packaging to prevent errors in the PyPI workflow in the future.

DM-28543: Fix rst error in long_description and add packaging check

---

CHANGELOG.rst
documenteer/conf/pipelines.py

Will be released as documenteer 0.6.5.

DM-28802: Update numpy and astropy intersphinx links

---

CHANGELOG.rst
documenteer/conf/pipelines.py

If the tag file is available, configure doxylink to use it. Otherwise, leave the "doxylink" dictionary empty.
This should prevent many problems with pure-python single-package documentation preview builds.

DM-28867: Conditionally configure doxylink in pipelines configuration

---

.travis.yml
CHANGELOG.rst
setup.py

This should resolve unordered list formatting issues with current technotes pinning to documenteer < 0.6

DM-32505: Update lsst-dd-rtd-theme to 0.2.4 (for 0.5.9 release)

---

CHANGELOG.rst
docs/conf.py
documenteer/conf/pipelines.py
documenteer/packagemetadata.py
documenteer/sphinxconfig/stackconf.py
setup.cfg
tests/test_packagemetadata.py

sphinx-jinja 2 adopted ``sphinx_jinja`` as its extension name, which requires an update to the `documenteer.conf.pipelines` configuration that uses it. To provides backwards support for sphinx-jinja 1, we're evaluating the environment's installed version of sphinx-jinja and customizing the extension name based on that. For this we've created a `documenteer.packagemetadata` module and `Semver` class, along with using `importlib.metadata` to get the version from a package.

DM-33988: Support sphinx-jinja 2, with backward compatibility for sphinx-jinja 1

---

CHANGELOG.rst
docs/conf.py
docs/pipelines/configuration.rst
docs/sphinx-extensions/docushare-reference.rst
docs/technotes/configuration.rst
src/documenteer/sphinxext/lsstdocushare.py
tests/test_sphinxext_lsstdocushare.py

- Add new roles
- sitcomtn
- rtn
- pstn
- ittn
- Add typing to the lsstdocushare extension
- Start trialling napoleon with sphinx_autodoc_typhints for generating the API reference

DM-34773: Add linking roles for SITCOMTN, etc, documents

---

CHANGELOG.rst
setup.py

The change in dependency pins to use numpydoc 1.2 principally fixes a numpydoc 0.8 incompatibility with Python 3.10. The move to Sphinx 1.8 is needed by numpydoc 1.2.
This is a release for Documenteer 0.5; new versions of Documenteer use the most recent Python versions.

DM-34954: Change pins to use Sphinx 1.8 and numpydoc 1.2 for Documenteer 0.5

---

CHANGELOG.rst
src/documenteer/conf/technote.py

Fixed the "Edit on GitHub" URL string construction in `documenteer.conf.technote`.

DM-35768: Fix the Edit on GitHub link for documenteer.conf.technote.

---

.pre-commit-config.yaml
src/documenteer/sphinxext/lssttasks/crossrefs.py

This updates the URL for the flake8 pre-commit hook (from GitLab to GitHub) and solves a flake8 issue that somehow got through all this time.

DM-35900: Update flake8 linter

---

src/documenteer/sphinxext/lssttasks/topics.py

`CmdLineTask` is being removed from pipe_base so will not be available in the future.
@jonathansick this is an interim fix that lets us handle the transition. I don't know if you intend to remove CmdLineTask support at some point in the future but this should fix the immediate problem I'm having with DM-35917.

DM-35917: Protect imports against CmdLineTask not being available

---

CHANGELOG.rst
src/documenteer/sphinxext/lssttasks/topics.py

This backports #126 to the 0.6 release series.

DM-35917: Back port CmdLineTask deprecation support for 0.6 release

---

CHANGELOG.rst
documenteer/sphinxext/lssttasks/topics.py
setup.cfg
setup.py

This backports #126 to the 0.5 release series.

DM-35917: Back port of CmdLineTask deprecation support for 0.5.12 release

---

docs/_rst_epilog.rst
docs/conf.py
docs/documenteer.toml
docs/index.rst
docs/project-guides/guides/extend-conf-py.rst
docs/project-guides/guides/toml-reference.rst
src/documenteer/conf/_toml.py
src/documenteer/conf/guide.py
src/documenteer/sphinxconfig/stackconf.py
src/documenteer/sphinxconfig/technoteconf.py
src/documenteer/sphinxrunner.py
src/documenteer/stackdocs/build.py
src/documenteer/stackdocs/doxygen.py
src/documenteer/stackdocs/pkgdiscovery.py
tests/test_conf_toml.py

This PR adds more support for common Sphinx configurations in `documenteer.toml`:
- nitpicky
- nitpick_ignore
- nitpick_ignore_regex
- intersphinx_mapping
- extensions
As well, we've made the Documenteer docs build cleanly thanks to leveraging `nitpick_ignore_regex`.

DM-36137: Support setting extensions, linkcheck and nitpick settings in documenteer.toml

---

docs/documenteer.toml
src/documenteer/conf/guide.py

The sphinx_click and autoprogram extensions automatically got added to the extensions list in documenteer.conf.guide, but really they shouldn't be in the default extension list and in fact they weren't part of the original [guide] dependencies extras anyhow.

DM-36156: Exclude click and autoprogram from guide config

---

docs/conf.py
docs/documenteer.toml
docs/project-guides/guides/toml-reference.rst
pyproject.toml
src/documenteer/conf/_toml.py
src/documenteer/conf/_utils.py
src/documenteer/conf/guide.py
tests/test_conf_toml.py

More features for Rubin user guides:
- Code cells now include a copy button
- Pages now feature a link to edit the source on GitHub (the github repo can be automatically detected from pyproject.toml metadata and the path of the docs directory relative to the repository root is discovered with GitPython).
- More configurations available through documenteer.toml, rather than conf.py
- disabling primary side bars on certain pages
- setting the Python API content directory for autoodapi
- setting the number header links to show in the nav bar

DM-36190: Enable additional features and configurations for user guides

---

docs/_rst_epilog.rst
docs/documenteer.toml
docs/guides/diagrams.rst
docs/guides/index.rst
docs/guides/overview.rst
pyproject.toml
src/documenteer/conf/guide.py

[Mermaid](https://mermaid-js.github.io/mermaid/#/) is a tool for generating diagrams for code. It is quickly becoming standard, with [GitHub's adoption](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/).
Right now we're defaulting to rendering the Mermaid code on the client side in the configuration, which does not require the CI environment or developer to have Mermaid installed. We may want to change this in the future for performance... potentially by detecting whether Mermaid is installed and opting to pre-render SVG files in the build in that case.
Mermaid doesn't handle deployment infrastructure diagrams. For that, we've documented how to intstall and use [diagrams](https://diagrams.mingrammer.com/). But since cloud infrastructure may be niche even within …

DM-36259: Include mermaid in the user guide extensions

---

pyproject.toml
src/documenteer/conf/guide.py

This comes via the sphinxext.opengraph extension published at https://github.com/wpilibsuite/sphinxext-opengraph. The basic configuration for the extension reuses already existing metadata compiled through the basic project configuration.
Supporting custom opengraph images will require more work, however there's a hint in https://github.com/wpilibsuite/sphinxext-opengraph/issues/66 that autogenerated preview images are in the works, so let's see how that plays out. 🎉

DM-36351: Add support for sphinxext.opengraph

---

CHANGELOG.md
README.md
docs/index.rst
src/documenteer/assets/rubin-pydata-theme.css

Improve the readability of the Rubin user guide theme:
- Increase base font size from 15px to 18px (which allows us to reduce line height from 1.65 to 1.5)
- Reduce contrast of table border lines in dark mode
- Fix a CSS bug that caused the GitHub icon in the top right to be smaller (now it's set to `var(--pst-font-size-icon)`, which should be future proof and the theme's intent.
Finally release as version 0.7.0.

DM-36665: Improve readability of documentation

---

docs/index.rst

Because of how setuptools_scm work, this will never be the release tag when tracking main, so this change is to reduce confusion from long version strings.

DM-36665: Drop version from homepage

---

.pre-commit-config.yaml
Makefile
src/documenteer/conf/_toml.py

- drop tox-pyenv since tox-pyenv doesn't appear to worth with tox version 4.
- Fixed small typo that caused a typing issue
- Refreshed pre-commit hooks

DM-37481: Fix emergent GitHub Actions issues

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
.gitignore
.pre-commit-config.yaml
pyproject.toml
src/documenteer/sphinxext/lssttasks/topiclists.py
tox.ini

- Update pre-commit plugins and apply a black formatting fix
- Don't require all Python versions to have run for collecting coverage results in tox

Update pre-commit plugins

---

src/documenteer/conf/guide.py

This is needed because the CDN for mermaid changed with version 10.

Temporarily pin mermaid to 9.4.0

---

CHANGELOG.md
docs/guides/toml-reference.rst
pyproject.toml

The extra path checking involved in the light and dark logos in the
html_theme_options isn't compatible with images installed via
html_static_path.

DM-38168: Pin pydata-sphinx-theme < 0.13

---

CHANGELOG.md
docs/guides/toml-reference.rst
pyproject.toml
src/documenteer/conf/_toml.py
src/documenteer/conf/guide.py

- Add a `sphinx.exclude` field for documenteer.toml to set what files/directories to exclude from the Sphinx build. This config appends to the Sphinx `exclude_patterns` variable.
- Add `requirements.txt` and `.venv`/`venv` to the default `exclude_patterns`.

DM-38388: Improve source exclusions for user guides

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
CHANGELOG.md
pyproject.toml
tox.ini

Pinned Sphinx < 7 for the `pipelines` and `technote` extras since their themes are not currently compatible with Sphinx 7 and later.

Pin Sphinx < 7 for pipelines, technote

---

CHANGELOG.md
pyproject.toml
src/documenteer/conf/guide.py
src/documenteer/conf/pipelines.py

Sphinx 6 stopped including jquery by default, but the pydata-sphinx-theme 0.12 release we're using doesn't include it. The temporary stop gap is to use sphinxcontrib-jquery.
https://github.com/sphinx-contrib/jquery/

DM-39580: Add sphinxcontrib-jquery (0.7 backport)

---

CHANGELOG.md
pyproject.toml
src/documenteer/conf/guide.py
src/documenteer/conf/pipelines.py

Use [sphinxcontrib-jquery](https://github.com/sphinx-contrib/jquery/) to ensure jQuery is available for user guide and Pipelines documentation builds.
Sphinx 6 stopped including jquery by default. Once we update to pydata-sphinx-theme 0.13 we can drop this extension.
Merge after #159

DM-39580: Add sphinxcontrib-jquery

---

docs/guides/openapi.rst
docs/sphinx-extensions/openapi.rst

Fix documentation examples for the documenteer.ext.openapi extension.

DM-39580: Document import of get_openapi

---

README.md
pyproject.toml

This also sneaks in a hot-fix constraint on sphinx-autodoc-typehints<1.23.0 to avoid a Sphinx version constraint conflict between sphinx-design (<7 currently) and sphinx-autodoc-typehints.

Fix typos on README

---

.gitignore
.pre-commit-config.yaml
CHANGELOG.md
Makefile
README.md
pyproject.toml
src/documenteer/sphinxrunner.py
src/documenteer/stackdocs/build.py
src/documenteer/stackdocs/packagecli.py
src/documenteer/stackdocs/stackcli.py

Adds a `-W` / `--warning-is-error` flag to the `package-docs build` and `stack-docs build` commands for Science Pipelines documentation builds. This flag causes Sphinx to treat warnings as errors, which is useful for CI builds.
Will be released as 0.8.0

DM-37783: Add -W flag to package-docs build / stack-docs build

---

CHANGELOG.md
src/documenteer/sphinxrunner.py
src/documenteer/stackdocs/build.py
src/documenteer/stackdocs/packagecli.py
src/documenteer/stackdocs/stackcli.py

This ports #164, which created the 0.8.0 release, to the main branch for future releases (e.g. 1.0.0). Also fixes the issue with the `help` subcommand not working on sub-commands of `stack-docs` and `package-docs`.

DM-25337: Add -W (warnings as errors) and `-n` nitpicky mode for stack-docs / package-docs build

---

CHANGELOG.md
pyproject.toml

Pin Pydantic < 2. This is meant as a temporary measure to get a stable
PyPI release for guide and technote users while we put out a release
that is compatible with both Pydantic v1 and v2.

DM-39884: Pin Pydantic < 2 (0.8.3 release)

---

CHANGELOG.md
pyproject.toml

This pins pydantic < 2 for the main line development branch.

DM-39884: Pin pydantic < 2.0.0

---

.github/workflows/ci.yaml

This is to double check that a release published-based workflow is getting the right package version. We'll revert this change to re-enable PyPI uploads when we're confident.

DM-39837: Check package version in GitHub Action release published event

---

.github/workflows/ci.yaml
tox.ini

The package isn't installed in the publish action job, of course.

DM-39837: Do version check in tox.ini

---

CHANGELOG.md
pyproject.toml

We already make this pin for technotes and pipelines; we've seen reports now of an incompatibility with guides too.

DM-40228: Pin Sphinx < 7 for guides (0.8.4 release)

---

.github/workflows/dependencies.yaml

This will update the pre-commit hooks on a periodic basis. Dependabot
will update github actions.

DM-40684: Add Neophile-based dependency update

---

pyproject.toml

It's necessary to always use technote from PyPI in order to get the generated theme assets.

DM-40815: Update to technote 0.3.0a2

---

changelog.d/20231012_194757_jsick_DM_41179.md
pyproject.toml
src/documenteer/requestsutils.py
src/documenteer/templates/technote/sections/header-article.html

This version changed the jinja context variable so that the metadata is now accessed via a new metadata attribute, rather than from the "toml" representation.

DM-41179: Update to technote 0.3.0a7

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
CHANGELOG.md
changelog.d/20231018_165310_jsick_DM_41214.md
demo/rst-technote/.gitignore
demo/rst-technote/index.rst
docs/_rst_epilog.rst
docs/documenteer.toml
docs/sphinx-extensions/githubbibcache.rst
docs/sphinx-extensions/index.rst
docs/sphinx-extensions/lsst-pybtex-style.rst
pyproject.toml
src/documenteer/conf/technote.py
src/documenteer/ext/githubbibcache.py
src/documenteer/templates/technote/sections/sidebar-primary.html
tox.ini

The new extension, `documenteer.ext.githubbibcache`, can fetch and locally cache bibtex files from one or more public GitHub repositories. These bibfiles are automatically added to `sphinxcontrib-bibtex`'s `bibtex_files` configuration.
Rubin technotes are now configured to automatically cache all bibfiles from the https://github.com/lsst/lsst-texmf repository. The `sphinxcontrib-bibtex` extension is available to technotes as well.
Because of a bug found in docutils <0.20 where it adds an extraneous and unclosed `<div>` element to the page when the `bibliography` directive from sphinxcontrib-bibtex is used, we're now requiring Sphinx>=7 for Documenteer. This in turn enables us to upgrade to docutils 0.20 and later.

DM-41214: Add a GitHub-based bibtex file cache extension

---

.github/SUPPORT.md
docs/_rst_epilog.rst
docs/documenteer.toml
docs/guides/pipelines/cpp-api-linking.rst
docs/technotes/_templates/README.md
docs/technotes/_templates/README.rst
docs/technotes/document-status.rst
docs/technotes/index.rst
docs/technotes/migrate.rst

This new documentation describes how to migrate an existing technote to use the technote.lsst.io format with Documenteer 1.0.

DM-41327: Document migration of technotes to new format

---

changelog.d/20231128_164718_jsick_DM_41781.md
demo/rst-technote/technote.toml
docs/technotes/migrate.rst
pyproject.toml

This version of technote changes the `technote.toml` keys for describing names.

DM-41781: Update to technote 0.5

---

.pre-commit-config.yaml
MANIFEST.in
changelog.d/20231212_141904_jsick_DM_42023.md
docs/_rst_epilog.rst
docs/technotes/migrate.rst
pyproject.toml
src/documenteer/cli.py
src/documenteer/services/__init__.py
src/documenteer/services/technoteauthor.py
src/documenteer/services/technotemigration.py
src/documenteer/storage/__init__.py
src/documenteer/storage/authordb.py
src/documenteer/storage/latex.py
src/documenteer/storage/localtemplates.py
src/documenteer/storage/localtemplates/technote/Makefile
src/documenteer/storage/localtemplates/technote/README.rst
src/documenteer/storage/localtemplates/technote/ci.yaml
src/documenteer/storage/localtemplates/technote/conf.py
src/documenteer/storage/localtemplates/technote/dependabot.yml
src/documenteer/storage/localtemplates/technote/gitignore
src/documenteer/storage/localtemplates/technote/pre-commit-config.yaml
src/documenteer/storage/localtemplates/technote/requirements.txt
src/documenteer/storage/localtemplates/technote/tox.ini
src/documenteer/storage/technotetoml.py
tests/data/authordb.yaml
tests/services/technotemigration_test.py
tests/storage/authordb_test.py
tests/storage/technotetoml_test.py

- New command-line interface for technote authors.
- `documenteer technote migrate` automates to the process of migrating an old technote to the new format.
- `documenteer technote add-author` adds an author to a technote's `technote.toml` file using data from the `authordb.yaml` file in https://github.com/lsst/lsst-texmf.
- `documenteer technote sync-authors` refreshing author information in a `technote.toml` file with information from the `authordb.yaml` file. This requires that individual authors have `internal_id` fields to correlate with `authordb.yaml`.
The motivation for adding the `add-author` and `sync-authors` commands is to help technote authors use information from lsst-texmf's authordb.yaml file to populate author information in technote.toml. Using these commands ensures …

DM-42023: Add documenteer technote add-author and sync-authors commands

---

src/documenteer/services/technotemigration.py

Ensure that new technotes have `license.id` information in their metadata.

DM-42144: Include license.id in migration template

---

CHANGELOG.md
changelog.d/20240130_174434_jsick_DM_42705.md
pyproject.toml
src/documenteer/conf/_toml.py
src/documenteer/conf/technote.py

This version of technote defaults the `date_modified` metadata to the build time if a date isn't explicitly set. Also improves the CSS for code samples.
Additional cahgnes in documenteer:
- Add `sphinx_design` as a default extension for technotes.
- If the `version` field in `documenteer.toml` isn't set, and the project isn't a Python package, then the default value is now "Latest." The former default, None, was invalid.

Update to technote 0.7

---

changelog.d/20240213_094921_jsick_guide_examples.md
docs/guides/pyproject-configuration.rst

Update to the Python project configuration guide for `documenteer.toml` to use an example project other than "Documenteer" in the examples. Also emphasize the requirement that the project must be installed to use the `[project.python]` configuration in `documenteer.toml`.

Improve guide for project.python table configuration

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
.github/workflows/dependencies.yaml
CHANGELOG.md
changelog.d/20240213_094921_jsick_guide_examples.md
changelog.d/20240221_130347_jsick_DM_42967.md
pyproject.toml

This is required by pybtex, which is used by documenteer.ext.bibtex. Ideally pybtex will switch to importlib.metadata so that this dependency will no longer be required.

DM-42967: Add setuptools as a dependency

---

CHANGELOG.md
changelog.d/20240411_130215_jsick_DM_43749.md
demo/ipynb-technote/index.ipynb
demo/md-technote/index.md
demo/rst-technote/index.rst
docs/sphinx-extensions/jira-reference.rst
src/documenteer/conf/guide.py
src/documenteer/conf/pipelines.py
src/documenteer/ext/jira.py
tests/ext/jira_test.py
tests/test_conf_toml.py

- Update `jira_uri_template` configuration default to `https://rubinobs.atlassian.net/browse/{issue}`. This will make all :jira:, :jirab:, and :jirap: roles point to the new Jira instance for Rubin Observatory.
- Drop `jira.lsstcorp.org` from the linkcheck ignore list defaults for `documenteer.config.guide` since that instance is no longer being used.
- Replace `jira.lsstcorp.org` URLs in documentation to `rubinobs.atlassian.net`.

DM-43749: Update jira_uri_template default to point to rubinobs.atlassian.net

---

.pre-commit-config.yaml
changelog.d/20240430_155714_jsick_DM_44137.md
demo/ipynb-technote/extra-notebook.ipynb
demo/ipynb-technote/subdir/subdir-notebook.ipynb
pyproject.toml
src/documenteer/conf/__init__.py
src/documenteer/conf/_utils.py
src/documenteer/conf/technote.py
src/documenteer/ext/githubbibcache.py
src/documenteer/ext/lssttasks/pyapisummary.py
tests/test_conf_utils.py

This configuration function is for technotes to exclude rst, md, and ipynb files that aren't the index file. Also includes small fixes due to updates in Sphinx:
- Technotes ignore files in the repository with `.md`, `.rst`, and `.ipynb` extensions if they aren't the index file. Since technotes are single-page documents, only the index file should be used as a source file. This change lets authors include auxillary notebooks with their technotes without having to explicitly exclude them from the technote build process. This is implemented with `technote.conf.extend_excludes_for_non_index_source`.
- In `documenteer.ext.lssttasks`, attempt to import `_pseudo_parse_arglist` from `sphinx.domains.python._annotations` before falling back to the `sphinx.domains.python` module. Ultimately this is …

DM-44137: Add extend_excludes_for_non_index_source

---

changelog.d/20240502_153501_jsick_DM_43638.md
demo/rst-technote/index.rst
pyproject.toml
src/assets/rubin-technote/styles/components/_article-header.scss
src/assets/rubin-technote/styles/components/_authors.scss

This change fixes the baseline misalignment for monospace text in technotes.

DM-43638: Update to technote 0.8 to fix baseline alignment for monospace text in technotes

---

CHANGELOG.md
changelog.d/20240711_142152_jsick_DM_44542.md
demo/md-technote/index.md
docs/technotes/index.rst
docs/technotes/wide-content.rst
pyproject.toml
src/assets/rubin-technote/styles/_hacks.scss

Update to the technote 0.9 release, which switches technotes to a two column layout. It also provides a `technote-wide-content` utility class that allows block content like tables, code blocks, and figures to span the full width of the page. This is useful for displaying inherently wide content while respecting the readability of the text column.

DM-44542: Adopt technote 0.9 and wide content utility class

---

changelog.d/20241010_133336_danfuchs_mermaid_compat.md
pyproject.toml

[Sphinx 8.1.0](https://github.com/sphinx-doc/sphinx/compare/v8.0.2...v8.1.0) contains [a commit](https://github.com/sphinx-doc/sphinx/pull/12762/files#diff-a4c6bf1492ef480b94af82c988f64ca56fa256fab0ed043a5ad3d4043f89a645L14) that removes the `ExtensionError` export from the `sphinx.util` package. This currently breaks the [sphinxcontrib-mermaid](https://github.com/mgaitan/sphinxcontrib-mermaid) dependency:
```
File "/home/danfuchs/src/safir/.nox/docs-clean/lib/python3.12/site-packages/sphinxcontrib/autoclassdiag.py", line 3, in <module>
from sphinx.util import ExtensionError, import_object
ImportError: cannot import name 'ExtensionError' from 'sphinx.util' (/home/danfuchs/src/safir/.nox/docs-clean/lib/python3.12/site-packages/sphinx/util/__init__.py)
```
Pin to < 8.1.0 for now until this …

DM-46777: sphinx < 8.1.0

---

changelog.d/20241010_133336_danfuchs_mermaid_compat.md
pyproject.toml
src/documenteer/conf/guide.py
src/documenteer/ext/remotecodeblock.py

* Set a lower bound on sphinxcontrib-mermaid to <=1
* Revert the Sphinx pin because this fixes the compatibility issue
* Ditch the `mermaid_version` pin because this fixes https://github.com/mgaitan/sphinxcontrib-mermaid/issues/110
* Ignore an import that mypy 1.12 doesn't consider re-exported anymore (it's renamed with `as`, not sure if that's a mypy bug, or if those are the real rules and it's a mypy fix)
Tested:
* Phalanx docs build
* [DMTN-234](https://dmtn-234.lsst.io/#tokens) build

DM-46777: Add a lower bound on sphinxcontrib-mermaid, revert sphinx pin

---

changelog.d/20250203_175511_jsick_DM_48755.md
docs/_rst_epilog.rst
docs/technotes/start-a-technote.rst

We've turned off the orginal sqrbot-jr in the former LSSTC workspace. Squarebot is the bot going forwards.

DM-48755: Point to Squarebot in rubin-obs Slack in technote documentation

---

docs/_rst_epilog.rst

This correction uses the app_redirect endpoint to correctly put any user into a DM with squarebot (see https://api.slack.com/reference/deep-linking#app_or_bot).

DM-48755: Fix squarebot app link

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
.prettierignore
CHANGELOG.md
changelog.d/20250219_135934_jsick_DM_49037.md
package-lock.json
package.json
pyproject.toml
src/assets/rubin-technote/styles/_properties.scss
src/documenteer/assets/rubin-pydata-theme.css
tox.ini

Pin Sphinx to avoid compatibility issues with the sphinxcontrib-bibtex extension, preparing for the 1.4.3 release.

DM-49037: Pin Sphinx < 8.2 for compatibility with sphinxcontrib-bibtex

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
.pre-commit-config.yaml
.prettierignore
changelog.d/20250219_160628_jsick_DM_49037.md
package-lock.json
package.json
pyproject.toml
src/assets/rubin-technote/styles/_properties.scss
src/documenteer/assets/rubin-pydata-theme.css
tox.ini

Transition from using a pre-commit hook for Prettier to running it directly within the Tox lint environment due to lack of support. Update the test matrix to include Python 3.13 and implement Slack notifications for cron test failures. Pin Sphinx to a version below 8.2 to avoid compatibility issues with the `sphinxcontrib-bibtex` extension. Reformat files with Prettier 3.5.1.

DM-49037: Run Prettier directly from tox / update test configurations / Pin Sphinx < 8.2

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml
changelog.d/20250224_102742_jsick_graphviz_ci.md

- Use ts-graphviz/setup-graphviz for setup graphviz, needed for docs builds
- Ensure that the full CSS and JS assets are built in more environments. For example, ensure they're available for documentation builds.

Ensure graphviz is installed in GitHub Actions

---

.github/workflows/ci-cron.yaml

Enables manual starts of the periodic CI workflow.

Allow ci-cron to start via workflow_dispatch

---

changelog.d/20250711_114447_jsick_nitpick_ignore.md
src/documenteer/conf/_utils.py
src/documenteer/conf/guide.py
src/documenteer/conf/technote.py

Introduce a centralized approach for nitpick ignore patterns to streamline documentation processes and reduce manual configurations.

Centralize nitpick ignore patterns

---

.claude/.gitignore
CLAUDE.md
changelog.d/20250815_125308_jsick_remotecodeblock_typing.md
src/documenteer/ext/remotecodeblock.py

remotecodeblock uses the same line highlighting syntax as the LiteralInclude directive. In Sphinx 7 this function was imported as parselineno, but in Sphinx 8 it became parse_line_num_sec after a migration period. To avoid this migration, and  since the function is
fairly self-contained, we're vendoring it directly into the Sphinx extension here.

Fix parse_line_num_spec import in remotecodeblock with vendoring

---

changelog.d/20250902_161655_danfuchs_DM_52367.md
src/documenteer/conf/_utils.py

- Add `sentry_sdk` to default non-intersphinx packages
- Ignore `TypeAliasType` due to sphinx bug
- Fix `nitpick_ignore_regex` regexes, they weren't being applied due to a missing `.`
- Ignore `asyncio.Event`, it has the same problem as `asyncio.Lock`

More autodoc/automodapi/autodoc_pydantic workarounds
