CHANGELOG.rst
documenteer/sphinxext/lsstdocushare.py

Note that this requires [IHS-1818](https://jira.lsstcorp.org/browse/IHS-1818), so it won't work at present. However, I wanted to submit the PR before I forgot..!

Add LSO document type.

---

CHANGELOG.rst
documenteer/conf/pipelines.py
documenteer/conf/pipelinespkg.py
documenteer/conf/technote.py

This configuration system is intended to be used by simply importing the module's contents into a Sphinx `conf.py` file. This approach should solve the recursion errors we saw from the previous method that injected a dictionary into the global namespace.

DM-20866: Introduce new configuration system

---

CHANGELOG.rst
documenteer/sphinxconfig/stackconf.py
setup.py

- Add sphinx-click dependency to pipelines extra
- Add sphinx_click.ext extension to stackconf.

DM-24411: Add sphinx_click.ext to stack documentation projects (0.5.8 release)

---

CHANGELOG.rst
README.rst
docs/index.rst
docs/pipelines/build-overview.rst
docs/pipelines/package-docs-cli.rst
docs/pipelines/stack-docs-cli.rst
setup.cfg

This PR has the final prep for the 0.6 documenteer release.

DM-27020: Version 0.6 release

---

.github/dependabot.yml
.github/workflows/ci.yaml
pyproject.toml
tests/test_ext_autocppapi.py
tests/test_stackdocs_doxygentag.py

General maintenance of our testing infrastructure
- Add Python/tox caching for GitHub Actions
- Enhance dependabot config
- Improve tox and isort configurations

DM-34231: Maintain GitHub Actions and dependabot

---

.github/workflows/ci.yaml
CHANGELOG.rst
docs/sphinx-extensions/docushare-reference.rst
src/documenteer/sphinxext/lsstdocushare.py

The tstn reStructuredText role makes it easy to link to TSTN documents.

DM-35443: Add tstn role

---

.github/workflows/ci-cron.yaml

- Fix typo in setting the python-version
- Ensure the full repo is retrieved for testing the git-based metadata introspection.

Fix issues in the ci-cron workflow

---

.pre-commit-config.yaml
CHANGELOG.md
src/documenteer/conf/_toml.py
src/documenteer/conf/guide.py
src/documenteer/sphinxext/lssttasks/topiclists.py

This backports #149 for the 0.7.x release series.

Backport mermaid 0.9.0 pin to documenteer 0.7.x

---

CHANGELOG.md
pyproject.toml
src/documenteer/conf/guide.py

Backports #155 to Documenteer 0.7

DM-38388: Backport for 0.7

---

.github/workflows/ci.yaml

This demonstrates the lsst-sqre/build-and-publish-to-pypi action from https://github.com/lsst-sqre/build-and-publish-to-pypi/pull/5

DM-39837: Try DM-39837 version of pypi-publish action

---

.github/workflows/ci-cron.yaml
.github/workflows/ci.yaml

Adopt lsst-sqre/build-and-publish-to-pypi@v2

---

CHANGELOG.md
pyproject.toml

DM-40228: Pin sphinx < 7 (main)

---

pyproject.toml

This will help us co-develop technote with documenteer.

DM-40815: Install technote from its main branch

---

pyproject.toml

This version should package assets correctly.

DM-40815: Update to technote 0.3.0a3

---

CHANGELOG.md
pyproject.toml

This version improves the CSS for content and makes the sidebars "sticky" to the viewport.

DM-40967: Update to technote 0.3.0a6

---

docs/technotes/migrate.rst

Fix typo that named manifest.yaml instead of metadata.yaml

Update technote migration

---

changelog.d/20240102_155845_jsick_3.md
src/documenteer/services/technotemigration.py

The red X was scary and implied failure

Change file deletion icon to trashcan

---

docs/technotes/edit-on-github.rst

Fix docs typo

---

changelog.d/20250827_142644_jsick_DM_52208.md
docs/guides/configuration.rst
docs/index.rst
docs/technotes/_templates/README.md
docs/technotes/_templates/README.rst
docs/technotes/edit-locally.rst
docs/technotes/index.rst
docs/technotes/migrate.rst
docs/technotes/references.rst
src/documenteer/storage/localtemplates/technote/README.rst

- Add docs on using sphinxcontrib-bibtex in technotes
- Other documentation cleanup.

DM-52208: Add documentation on creating references in technotes

---

changelog.d/20250903_155153_jsick_DM_52199.md
demo/rst-technote/index.rst
demo/rst-technote/local.bib
src/documenteer/ext/bibtex.py

Make sure there is a link to ascl.net

DM-52199: Add support for ASCL @software bib entries
